### ISSUE TITLE
VSCode extension doesn't seem to be working correctly.

### ISSUE THREAD

**Issue by Ayub-Begimkulov** [codeque-co/codeque#10]
I just found out about this project and decided to try it out, since my task right now a lot of finds and replaces in the project. 

However this extension doesn't seem to work. When I switch to CQ in my sidebar I get this error:

```
Error loading webview: Error: Could not register service workers: InvalidStateError: Failed to register a ServiceWorker: The document is in an invalid state..
```

I'm using macos m1, vscode version:

```shell
code --version
1.74.3
97dec172d3256f8ca4bfb2143f3f76b503ca0534
arm64
```

If you need any additional info I'm happy to help. Thanks for you awesome work!

**Comment by jayu** [comment]
I'm also on MacOS m1 and the same vscode version and i works. What's your OS version?
Maybe restarting vscode / reinstalling extension would help ?

**Comment by Ayub-Begimkulov** [comment]
Yes, it seems to work, but can catch this error from time to time. However, quitting vscode and opening helps.

Not sure how we can track it. Let's close it for now and I'll reopen it if the problem will keep happening.
