### ISSUE TITLE
Follow symlink

### ISSUE THREAD

**Issue by nrome-n** [codeque-co/codeque#11]
The extenuation really good and fast my only issue is when using the search and selecting symlink folder no results are returned.

just as an explanation the symlink is to git repo `odoo` that is not part of the code i am writing but i need search regularly

**Comment by jayu** [comment]
Hello, thanks for the report!

I need some more information about this issue.

- What is you operating system
- Do you symlink directory of file
- Where the symlink is in the directory structure of the project that you have opened in VSCode ? Is it in a path that is not ignored by .gitignore ?

**Comment by nrome-n** [comment]
Hi @jayu 
sorry for not following up with the issue 
I am using mac os 14.0,
all project 
|___ odoo 
|         |___ odoo 16
|____Project
            |___ symlink of odoo 16

odoo 16 symlink is in the .gitignore because if just for search

**Comment by jayu** [comment]
Thanks @nrome-n.

I didn't checked if symlinks work, but if your symlinks is in git ignore, it won't be tracked anyway, unless you allow for search in ignored files.

Let me know if that works.

Also did you consider using vscode workspaces?

You can basically open two separate folders in one vscode window. This way you can workaround using symlinks :D

**Comment by nrome-n** [comment]
Hi @jayu 
i tried search in this file and enable searching in ignored files but no results. i only user duplicate workspaces to open the same project on my seconds.

The reason i am using symlinks. Is that i have multiple symlinks in a folder and add this folder to my project template. 
so i can update all them at the sometime git pull. 
Not sure if workspaces will work but i will try it 

Thank u of the great plugin

```
 all project Folder
  |___ odoo 
  |         |___ odoo 16 com [git]
  |         |          |___ addons
  |         |          |        |____ base [symlinked]
  |         |          |___  odoo
  |         |                   |___ addons [symlinked]
  |         |___ odoo Ent [git][symlinked]
  |
  |____Project folder
              |___ odoo Folder
                          |___ base [symlinked]
                          |___ addons [symlinked]
                          |___ odoo Ent [symlinked]

```

**Comment by jayu** [comment]
Hi @nrome-n, CodeQue should now follow symlinks from version `0.25.1.`

https://marketplace.visualstudio.com/items?itemName=CodeQue.codeque

Please let me know if that fix worked for you 🤞

**Comment by nrome-n** [comment]
Hi @jayu, works amazingly thank you 🤩, i tried it with searching in ignored files because of .gitignore.

**Comment by jayu** [comment]
I'm glad it works! Happy searching 😸
