### ISSUE TITLE
Please provide extensions through open-vsx.org as well

### ISSUE THREAD

**Issue by mehrad-rafigh** [codeque-co/codeque#2]
Hi there, 

would love to try your plugin, but I am using VSCodium and can only install extensions that have been released on open-vsx.org as well.

You can follow this link https://github.com/eclipse/openvsx/wiki/Publishing-Extensions to publish your extension to open-vsx as well. 

Thanks!

**Comment by jayu** [comment]
Hi! Thank you! I didn't realise that, I will do it definitely next week!

**Comment by mehrad-rafigh** [comment]
Thanks @jayu

**Comment by jayu** [comment]
Hey mate @mehrad-rafigh, I've pubished it for ya 🥳 

[https://open-vsx.org/extension/CodeQue/codeque](https://open-vsx.org/extension/CodeQue/codeque)

Let me know if that works, where I can download non-official version of VSCode to test it myself ?

**Comment by mehrad-rafigh** [comment]
@jayu thanks for the work you done and a happy new year!

I am using https://github.com/VSCodium/vscodium as an alternative to vscode. Its basically vscode but without the microsoft tracking that is enabled.

**Comment by mehrad-rafigh** [comment]
@jayu I installed the extension a minute ago and it works like a charm!! Thank you very much for your work!!!!

**Comment by jayu** [comment]
🙏
