### ISSUE TITLE
CodeVue only shows 4 files with matches, even if there are more files with matches

### ISSUE THREAD

**Issue by ThomasVogelpohl** [codeque-co/codeque#20]
Hi Jakub,

I think you have started a very cool new tool, thanks for that !!!

While using CodeQue, I found a rather odd issue. .... it seems CodeQue does not want to count higher than decimal 4   ;-)
Means, it displays just 4 files with matches, even if there are more files in the search folder with matches.

Now that is an accusation, so let me explain:

In the following screenshot you see a screenshot of VSCode.
I have more than 15 log files in a folder.
Then I do a simple search, on the left with the in-build VSCode Search. On the right with CodeQue

CodeVue got the correct results per file, but only listed 4 files.
And CodeVue listed the only the 4 files with the lowest number of matches.
(You can check the bubbles in the VSCode search, which shows the number of matches in the file.

I am sure I am doing something wrong, but what ?

Thanks, Thomas

<img width="1720" alt="image" src="https://github.com/codeque-co/codeque/assets/3432527/ac5a5db2-72f1-4e6b-8bf3-7b11611d9494">

**Comment by jayu** [comment]
Hey @ThomasVogelpohl Did you manage to resolve your issue based on the above information ?

**Comment by jayu** [comment]
I'm closing the issue due to inactivity
