### ISSUE TITLE
Weird matching

### ISSUE THREAD

**Issue by hediet** [codeque-co/codeque#21]
(search for `transaction(tx => $$$)` in the vscode repository)

![Image](https://github.com/codeque-co/codeque/assets/2931520/6b0b9764-d886-43d1-98ab-e7375b96f6b3)

Why is `` }`) `` not included in the first match, but is included in the third match?

**Comment by jayu** [comment]
Thanks for the bug report!

I've checked it and it seems to be just match highlighting bug. 

Match location is correct when match link is opened in editor.

It perhaps has something to do with tabs used for file indentation (instead of spaces).

I will work on a fix soon !

**Comment by jayu** [comment]
This has been fixed in `0.27.0` -> [Marketplace](https://codeque.co/r/vsc)
