### ISSUE TITLE
Identifier '$$' has already been declared.

### ISSUE THREAD

**Issue by cesaryuan** [codeque-co/codeque#33]
Thanks for your excellent extension! It helps me a lot.

In addition, I still have one question: How to use multiple $$ in query. For example, the following query will throw error.

```
const $$ = 1;
const $$ = 2;
```
![image](https://github.com/codeque-co/codeque/assets/35998162/cfc6a6b2-f014-4eeb-be93-7da38dd930bb)

**Comment by jayu** [comment]
I'm glad it serves you 😊 

There is undocumented (yet) feature which you can use to set given wildcard a reference. Simply add `_someName` after the wildcard like this `$$_someName` 

Your query could look like this

```ts
const $$_var1 = 1;
const $$_var2 = 2;
```

Also, references can be used to link different identifiers inside the query, eg.

```ts
function myFn($$_arg) {
    return $$_arg
}
```

Using refs in this query will ensure that returned identifier is the same as identifier in parameters

**Comment by cesaryuan** [comment]
Thanks! It works 🥰
