### ISSUE TITLE
Match bug with `include-with-order` mode 

### ISSUE THREAD

**Issue by cesaryuan** [codeque-co/codeque#36]
In `include-with-order` mode, query `function func($$, arg2 = "test") {}` not match `function func(arg1, arg2 = "test") {}`.

But in `exact` and `include` mode, it matches.

**Comment by jayu** [comment]
Good spot! Thank you. I will work on this bug soon. It might be related to some other but I found regarding wildcards in `include-with-order` mode, which I wanted to also fix soon.

**Comment by jayu** [comment]
It has been fixed in extension version `0.29.0` and core version `0.6.1` 🥳
