### ISSUE TITLE
This is an amazing extension! Thank you so much for making it!

### ISSUE THREAD

**Issue by niamleeson** [codeque-co/codeque#37]
Just wanted to mention this extension is absolutely mindblowing and useful!

**Comment by jayu** [comment]
Thank you! I really appreciate it!

You can [add a review](https://marketplace.visualstudio.com/items?itemName=CodeQue.codeque&ssr=false#review-details) on Visual Studio Code marketplace if you like.

Also make sure to [join newsletter](https://jayu.dev/newsletter) to not miss updates. 

I'm working on extended query syntax and replace algorithm. Early versions will be available for newsletter subscribers :)
