### ISSUE TITLE
Error in extension console

### ISSUE THREAD

**Issue by paustint** [codeque-co/codeque#41]
Not a big deal - just thought I would report it since it seems like it should probably be a handled case. I was looking in the console for some other unrelated extension and noticed an error from this extension. It isn't hurting anything, so feel free to close the ticket if you want.

![image](https://github.com/codeque-co/codeque/assets/5461649/ed4756cb-7db0-4627-a2c8-4ae4165c9945)

**Comment by jayu** [comment]
Thank you for the report! I'm aware of that, it's no harm, but it should be handled better since it's expected. I will improve this :)

**Comment by jayu** [comment]
Fixed in 0.32.1
