### ISSUE TITLE
Find ok - replace nothing happens

### ISSUE THREAD

**Issue by edikaufmann** [codeque-co/codeque#44]
upfront, I'm competely new to codeque ...!
In VS code I can find all my strings  with 'codeque extension' BUT when clicking replace nothing happens.

What  am I most probably missing?

Again, this is my very first use of codeque
![CQ 1](https://github.com/user-attachments/assets/16a66aa0-de64-4261-96fe-a011496159b4)
thanks for your time, ed

**Comment by jayu** [comment]
Hi, the replace feature is a stub feature now, it just shows this modal.  I've decided to add it to track the interest in the replace feature.

 
<img width="621" alt="image" src="https://github.com/user-attachments/assets/ef4e0a28-7fec-44de-b1e6-a00d9719b385" />

**Comment by edikaufmann** [comment]
does this mean it is one-time fee of 17€ (37€) ? Or, is this just the newsletter?
what about updates after 1 year?
thanks for clarifying
ed K

**Comment by edikaufmann** [comment]
In fact all I want to know:
what do I need to do to be able to find/replace in my html files
thanks, ed

**Comment by edikaufmann** [comment]
didn't get an answer

**Comment by edikaufmann** [comment]
tried to: 
subscribe to get early bird price !
never got asked to pay. I will close this ticket
