### ISSUE TITLE
Invalid regular expression caused by '/' in .gitignore on Windows

### ISSUE THREAD

**Issue by staszekj** [codeque-co/codeque#8]
Extension is absolutely great!

However on Windows
.gitIgnore files sometimes contains:
/dist/
or other similar phrases with '/'

what causes:
Invalid regular expression: /(?:^|\/)projects\my-project-name\dist\(?=$|\/$)/: Unmatched ')'

To make this extension working I just checked: 'Searched ignored files'

**Comment by jayu** [comment]
Thanks! I will check it, looks like there are some issues on Windows that I didn't spot. I didn't test edge cases on windows :D

**Comment by jayu** [comment]
The issue had been fixed in release `0.20.1` 🥳 

Thank you @staszekj for reporting a bug hence contributing to make CodeQue better!
