### ISSUE TITLE
Are VSCode workspaces supported?

### ISSUE THREAD

**Issue by NullEnt1ty** [codeque-co/codeque#9]
Hey, there!

The VSCode extension does seem to struggle with [workspaces](https://code.visualstudio.com/docs/editor/workspaces). It only searches files of the first project and when I limit the search to another project, the extension doesn't search any files.

The search results also don't include the project name in the file path which leads me to the question: Are workspaces supported yet? 🙂

**Comment by jayu** [comment]
Only first workspace is supported at the moment. I personally do not use multiple workspaces so I didn't prioritise that.

As a workspace user, what would be the expected behaviour @NullEnt1ty?

Should CodeQue always search all open workspaces or maybe it should be parameterized somehow?

I'm trying to understand what would be the best workflow

**Comment by NullEnt1ty** [comment]
I think CodeQue should mimic the behaviour of VSCode's search feature. VSCode searches in all folders in a workspace by default. You can limit the search to a specific folder.

For example:

![grafik](https://user-images.githubusercontent.com/966433/211495261-a25f6ac6-df86-49c8-9ad3-00242c322c22.png)

In this case "backend" is a folder in my workspace configuration. Notice that "backend" is not part of the resulting file tree because the search was limited to that folder. If I search across all workspace folders, the result looks like this:

(I collapsed the other workspace folders)

![grafik](https://user-images.githubusercontent.com/966433/211495938-117f54c6-8763-401b-a128-34fd776e12b6.png)

Thanks for your time so far!

**Comment by jayu** [comment]
Thank you! Looks like it's relatively low hanging fruit, I will grab it soon :D 
Except the file system collapsible tree in sidebar, it's planned for some other time as it requires more effort.

**Comment by jayu** [comment]
@NullEnt1ty  Workspaces support added in extension version `0.20.0` !

**Comment by NullEnt1ty** [comment]
Works great, thank you!
